### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ghost** [FarzaanaM/prj-rev-bwfs-dasmoto#7]
Satisfactory 👍 

Nice job reproducing the design mock! You've got a good handle on the material covered so far.

You've used classes very well, but try to use `div`s and classes to group together equivalent sections and in turn write more descriptive but maintainable CSS. Make sure you use relative file paths in your project so that your project is ready for others to use.

Make sure to come back to this project later on when you've learned about `flexbox` and media queries to make a mobile responsive version of the site. You're certainly capable of it and there's no reason why you can't leave this program without a few high quality portfolio pieces!

**Comment by FarzaanaM** [comment]
Thank you Steve.
